import { NormalizedEvent } from "@/lib/types";

function daysFromNow(days: number, hour: number, minute = 0): string {
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Madrid" }).format(new Date());
  const [year, month, day] = today.split("-").map(Number);
  const utcGuess = Date.UTC(year, month - 1, day + days, hour, minute, 0);

  const asMadridUtc = (instant: number) => {
    const parts = new Intl.DateTimeFormat("en-GB", {
      timeZone: "Europe/Madrid",
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      hourCycle: "h23",
    }).formatToParts(new Date(instant));
    const value = (type: string) => Number(parts.find((part) => part.type === type)?.value);
    return Date.UTC(value("year"), value("month") - 1, value("day"), value("hour"), value("minute"), value("second"));
  };

  return new Date(utcGuess + (utcGuess - asMadridUtc(utcGuess))).toISOString();
}

/**
 * Sample Barcelona listings used when Supabase isn't configured, so the site
 * is browsable locally before API keys and a database are wired up.
 */
export function getDemoEvents(): NormalizedEvent[] {
  const syncedAt = new Date().toISOString();

  const events: NormalizedEvent[] = [
    {
      id: "demo_jamboree_jazz",
      source: "eventbrite",
      source_url: "https://jamboreejazz.com/",
      title: "Late Night Jazz at Jamboree",
      description: "A classic Plaça Reial jazz set in Barcelona's longest-running basement club.",
      venue_name: "Jamboree Jazz",
      address: "Plaça Reial 17, 08002 Barcelona",
      latitude: 41.3797,
      longitude: 2.1752,
      start_datetime: daysFromNow(0, 22, 30),
      end_datetime: null,
      price_min: 18,
      price_max: 25,
      is_free: false,
      genre: "live-music",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_clubhouse_comedy",
      source: "eventbrite",
      source_url: "https://www.eventbrite.es/o/the-comedy-clubhouse-bcn-58689016343",
      title: "Friday Night Live — English Stand-Up",
      description: "International comics at Barcelona's dedicated comedy club.",
      venue_name: "The Comedy Clubhouse",
      address: "Via Laietana, 08003 Barcelona",
      latitude: 41.3856,
      longitude: 2.1774,
      start_datetime: daysFromNow(1, 21, 0),
      end_datetime: null,
      price_min: 12,
      price_max: 18,
      is_free: false,
      genre: "comedy",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_apolo_live",
      source: "ticketmaster",
      source_url: "https://www.sala-apolo.com/",
      title: "Live at Sala Apolo",
      description: "Touring bands and club nights in Poble-sec's landmark room.",
      venue_name: "Sala Apolo",
      address: "Carrer Nou de la Rambla 113, 08004 Barcelona",
      latitude: 41.3744,
      longitude: 2.1696,
      start_datetime: daysFromNow(2, 21, 0),
      end_datetime: null,
      price_min: 28,
      price_max: 35,
      is_free: false,
      genre: "live-music",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_razzmatazz",
      source: "ticketmaster",
      source_url: "https://www.salarazzmatazz.com/",
      title: "Club Night at Razzmatazz",
      description: "Five rooms of indie, electro, and touring DJs in Poblenou.",
      venue_name: "Razzmatazz",
      address: "Carrer dels Almogàvers 122, 08018 Barcelona",
      latitude: 41.3978,
      longitude: 2.1911,
      start_datetime: daysFromNow(3, 23, 0),
      end_datetime: null,
      price_min: 20,
      price_max: 28,
      is_free: false,
      genre: "clubbing",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_barts",
      source: "ticketmaster",
      source_url: "https://barts.cat/",
      title: "Concert at BARTS",
      description: "Mid-size touring show on Avinguda del Paral·lel.",
      venue_name: "BARTS",
      address: "Avinguda del Paral·lel 62, 08001 Barcelona",
      latitude: 41.375,
      longitude: 2.169,
      start_datetime: daysFromNow(5, 20, 0),
      end_datetime: null,
      price_min: 32,
      price_max: 45,
      is_free: false,
      genre: "live-music",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_velvet_jazz",
      source: "eventbrite",
      source_url: "https://www.eventbrite.es/o/50358669263",
      title: "Jazz Jam at Velvet Room",
      description: "Weekly jam with a house trio and rotating guests in Les Corts.",
      venue_name: "Velvet Room BCN",
      address: "Carrer de l'Aviació 5, 08029 Barcelona",
      latitude: 41.3806,
      longitude: 2.1278,
      start_datetime: daysFromNow(6, 20, 30),
      end_datetime: null,
      price_min: 15,
      price_max: 15,
      is_free: false,
      genre: "live-music",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_sant_jordi",
      source: "ticketmaster",
      source_url: "https://www.ticketmaster.es/",
      title: "Arena Show at Palau Sant Jordi",
      description: "Major touring production at Montjuïc's indoor arena.",
      venue_name: "Palau Sant Jordi",
      address: "Passeig Olímpic 5–7, 08038 Barcelona",
      latitude: 41.3631,
      longitude: 2.1526,
      start_datetime: daysFromNow(8, 21, 0),
      end_datetime: null,
      price_min: 55,
      price_max: 120,
      is_free: false,
      genre: "live-music",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_ocana_free",
      source: "eventbrite",
      source_url: "https://www.eventbrite.es/o/96768207773",
      title: "JazzOcaña — Free Live Jazz",
      description: "Sunday night New Orleans-rooted jazz on Plaça Reial. Free entry.",
      venue_name: "Ocaña",
      address: "Plaça Reial 13–15, 08002 Barcelona",
      latitude: 41.3801,
      longitude: 2.175,
      start_datetime: daysFromNow(6, 21, 0),
      end_datetime: null,
      price_min: 0,
      price_max: 0,
      is_free: true,
      genre: "live-music",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_poble_espanyol",
      source: "eventbrite",
      source_url: "https://www.poble-espanyol.com/",
      title: "Open-Air Festival Night at Poble Espanyol",
      description: "Outdoor stage on Montjuïc with DJs and live acts.",
      venue_name: "Poble Espanyol",
      address: "Avinguda Francesc Ferrer i Guàrdia 13, 08038 Barcelona",
      latitude: 41.3686,
      longitude: 2.1481,
      start_datetime: daysFromNow(10, 18, 0),
      end_datetime: null,
      price_min: 25,
      price_max: 40,
      is_free: false,
      genre: "festival",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_secret_comedy",
      source: "eventbrite",
      source_url: "https://www.eventbrite.es/o/secret-comedy-club-60403957483",
      title: "Secret Comedy Club — English Stand-Up",
      description: "Speakeasy-style English comedy in the city centre.",
      venue_name: "Secret Comedy Club",
      address: "Ciutat Vella, 08002 Barcelona",
      latitude: 41.3825,
      longitude: 2.1768,
      start_datetime: daysFromNow(4, 20, 30),
      end_datetime: null,
      price_min: 14,
      price_max: 14,
      is_free: false,
      genre: "comedy",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_bikini",
      source: "ticketmaster",
      source_url: "https://www.salabikini.com/",
      title: "Club Night at Sala Bikini",
      description: "Electronic and indie nights under L'Illa Diagonal.",
      venue_name: "Sala Bikini",
      address: "Avinguda Diagonal 547, 08029 Barcelona",
      latitude: 41.3894,
      longitude: 2.1365,
      start_datetime: daysFromNow(9, 23, 0),
      end_datetime: null,
      price_min: 18,
      price_max: 22,
      is_free: false,
      genre: "clubbing",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_palau_musica",
      source: "ticketmaster",
      source_url: "https://www.palaumusica.cat/",
      title: "Concert at Palau de la Música Catalana",
      description: "An evening in the Modernista concert hall in El Born.",
      venue_name: "Palau de la Música Catalana",
      address: "Carrer del Palau de la Música 4–6, 08003 Barcelona",
      latitude: 41.3875,
      longitude: 2.1752,
      start_datetime: daysFromNow(12, 19, 30),
      end_datetime: null,
      price_min: 28,
      price_max: 65,
      is_free: false,
      genre: "live-music",
      image_url: null,
      last_synced_at: syncedAt,
    },
  ];

  for (let day = 0; day < 7; day++) {
    events.push({
      id: `demo_duende_${day}`,
      source: "eventbrite",
      source_url: "https://www.eventbrite.es/o/115618506621",
      title: "Flamenco Show Barcelona El Duende by Tablao Cordobes",
      description: "Intimate flamenco in Tablao Cordobes' new Rambla theatre.",
      venue_name: "El Duende by Tablao Cordobes",
      address: "La Rambla 33, 08002 Barcelona",
      latitude: 41.3802,
      longitude: 2.1738,
      start_datetime: daysFromNow(day, 19, 0),
      end_datetime: null,
      price_min: 27,
      price_max: 42,
      is_free: false,
      genre: "live-music",
      image_url: null,
      last_synced_at: syncedAt,
    });
  }

  events.push(
    {
      id: "demo_clubhouse_comedy_next",
      source: "eventbrite",
      source_url: "https://www.eventbrite.es/o/the-comedy-clubhouse-bcn-58689016343",
      title: "Friday Night Live — English Stand-Up",
      description: "International comics at Barcelona's dedicated comedy club.",
      venue_name: "The Comedy Clubhouse",
      address: "Via Laietana, 08003 Barcelona",
      latitude: 41.3856,
      longitude: 2.1774,
      start_datetime: daysFromNow(8, 21, 0),
      end_datetime: null,
      price_min: 12,
      price_max: 18,
      is_free: false,
      genre: "comedy",
      image_url: null,
      last_synced_at: syncedAt,
    },
    {
      id: "demo_jackies",
      source: "eventbrite",
      source_url: "https://www.eventbrite.es/o/jackies-17539819258",
      title: "Jackies Open Air Daytime w/ Gerd Janson",
      description: "Open-air house at La Terrrazza. Table packages sit far above general admission.",
      venue_name: "La Terrrazza Barcelona",
      address: "Poble Espanyol, 08038 Barcelona",
      latitude: 41.3686,
      longitude: 2.1481,
      start_datetime: daysFromNow(4, 19, 0),
      end_datetime: null,
      price_min: 24.4,
      price_max: 1108.9,
      is_free: false,
      genre: "clubbing",
      image_url: null,
      last_synced_at: syncedAt,
    }
  );

  return events.sort((a, b) => a.start_datetime.localeCompare(b.start_datetime));
}

export function findDemoEvent(id: string): NormalizedEvent | null {
  return getDemoEvents().find((event) => event.id === id) ?? null;
}
